// ================================================================
// Netlify Serverless Function
// Auto-deployed at: /.netlify/functions/save
// ================================================================
// Environment variables to set in Netlify dashboard:
//   ADMIN_SECRET  — any secret string, used by Admin UI
//   GITHUB_TOKEN  — personal access token (repo scope)
//   GITHUB_REPO   — e.g. yourname/sangam-utsav
//   GITHUB_BRANCH — e.g. main
// ================================================================

exports.handler = async function(event) {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: JSON.stringify({ error: 'Method not allowed' }) };
  }

  const authHeader = event.headers['x-admin-token'];
  const ADMIN_TOKEN = process.env.ADMIN_SECRET || 'change-this-secret';
  if (authHeader !== ADMIN_TOKEN) {
    return { statusCode: 401, body: JSON.stringify({ error: 'Unauthorized' }) };
  }

  let body;
  try { body = JSON.parse(event.body); } catch(e) {
    return { statusCode: 400, body: JSON.stringify({ error: 'Invalid JSON' }) };
  }

  const { type, content } = body;
  if (!type || !content) {
    return { statusCode: 400, body: JSON.stringify({ error: 'Missing type or content' }) };
  }

  const GH_TOKEN  = process.env.GITHUB_TOKEN;
  const GH_REPO   = process.env.GITHUB_REPO;
  const GH_BRANCH = process.env.GITHUB_BRANCH || 'main';

  if (!GH_TOKEN || !GH_REPO) {
    return { statusCode: 500, body: JSON.stringify({ error: 'GitHub env vars not set in Netlify' }) };
  }

  const filePath = type === 'events' ? 'events.js' : 'config.js';
  const prefix = type === 'events'
    ? '// Auto-generated by Admin\nconst EVENTS_DATA = '
    : '// Auto-generated by Admin\nconst SITE_CONFIG = ';
  const fileContent = prefix + JSON.stringify(content, null, 2) + ';\n';

  try {
    const API = `https://api.github.com/repos/${GH_REPO}/contents/${filePath}`;
    const headers = {
      Authorization: `token ${GH_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    };

    const getRes = await fetch(`${API}?ref=${GH_BRANCH}`, { headers });
    const sha = getRes.ok ? (await getRes.json()).sha : undefined;

    const putRes = await fetch(API, {
      method: 'PUT', headers,
      body: JSON.stringify({
        message: `Admin: update ${filePath}`,
        content: Buffer.from(fileContent).toString('base64'),
        branch: GH_BRANCH,
        ...(sha ? { sha } : {})
      })
    });

    if (!putRes.ok) {
      const err = await putRes.json();
      return { statusCode: 500, body: JSON.stringify({ error: err.message }) };
    }

    return { statusCode: 200, body: JSON.stringify({ success: true, file: filePath }) };
  } catch(e) {
    return { statusCode: 500, body: JSON.stringify({ error: e.message }) };
  }
};
