// =============================================================
// SITE CONFIG — Auto-generated by Admin UI
// =============================================================
const SITE_CONFIG = {
  "siteName": "Rasārādhanaṃ",
  "tagline": "A Celebration of Indian Classical Arts, Culture and Erudition",
  "description": "A curated series of music, dance, discourse, and cultural gatherings celebrating the depth and continuity of Indian classical traditions.",
  "contactEmail": "rasaradhanam@gmail.com",
  "contactPhone": "+917349497814",
  "socialLinks": {
    "instagram": "https://instagram.com/sangamutsav",
    "youtube": "https://youtube.com/@sangamutsav"
  },
  "style": {
    "primaryColor": "#8B1A1A",
    "accentColor": "#C9922A",
    "backgroundColor": "#FDF8F0",
    "textColor": "#1A1208",
    "fontHeading": "Cormorant Garamond",
    "fontBody": "Lora",
    "cardStyle": "bordered",
    "heroPattern": "rangoli"
  }
};
