// =============================================================
// EVENTS DATA — Auto-generated by Admin UI
// =============================================================
const EVENTS_DATA = [
  {
    "id": "evt001",
    "title": "Thyagaraja Aradhana Sabha",
    "description": "A grand celebration of Thyagaraja's compositions featuring leading Carnatic vocalists performing the Pancharatna Kritis and rare compositions.",
    "date": "2025-02-14",
    "time": "17:00",
    "category": "Carnatic Vocal",
    "artists": [
      "Sudha Raghunathan",
      "T.M. Krishna"
    ],
    "venue": {
      "name": "Chowdiah Memorial Hall",
      "address": "Vyalikaval, Bengaluru, Karnataka 560003",
      "mapEmbedUrl": ""
    },
    "registrationEnabled": false,
    "registrationUrl": "",
    "image": "",
    "featured": true
  },
  {
    "id": "evt002",
    "title": "Sadir Utsav — Bharatanatyam Festival",
    "description": "A three-day Bharatanatyam festival showcasing performances by emerging and established dancers.",
    "date": "2025-03-08",
    "time": "18:30",
    "category": "Bharatanatyam",
    "artists": [
      "Alarmel Valli",
      "Malavika Sarukkai"
    ],
    "venue": {
      "name": "Ravindra Kalakshetra",
      "address": "J.C. Road, Bengaluru, Karnataka 560002",
      "mapEmbedUrl": ""
    },
    "registrationEnabled": true,
    "registrationUrl": "https://bookmyshow.com/events/sadir-utsav",
    "image": "",
    "featured": false
  },
  {
    "id": "evt003",
    "title": "Raga Rasa — An Evening of Hindustani Music",
    "description": "A contemplative evening of Khayal and Thumri by maestros of the Jaipur-Atrauli and Kirana gharanas.",
    "date": "2025-04-19",
    "time": "19:00",
    "category": "Hindustani Vocal",
    "artists": [
      "Rashid Khan",
      "Ashwini Bhide Deshpande"
    ],
    "venue": {
      "name": "Siri Fort Auditorium",
      "address": "August Kranti Marg, New Delhi 110049",
      "mapEmbedUrl": ""
    },
    "registrationEnabled": true,
    "registrationUrl": "https://insider.in/raga-rasa-2025",
    "image": "",
    "featured": true
  },
  {
    "id": "evt004",
    "title": "Natya Sangam — Classical Dance Symposium",
    "description": "Scholars and practitioners come together for a symposium on classical Indian dance.",
    "date": "2024-11-10",
    "time": "10:00",
    "category": "Dance Symposium",
    "artists": [
      "Leela Samson",
      "C.V. Chandrasekhar"
    ],
    "venue": {
      "name": "Sangeet Natak Akademi",
      "address": "Rabindra Bhavan, Ferozeshah Road, New Delhi 110001",
      "mapEmbedUrl": ""
    },
    "registrationEnabled": false,
    "registrationUrl": "",
    "image": "",
    "featured": false
  },
  {
    "id": "evt005",
    "title": "Veena Vaibhavam",
    "description": "A rare solo veena concert followed by a jugalbandi with flute.",
    "date": "2024-12-21",
    "time": "18:00",
    "category": "Carnatic Instrumental",
    "artists": [
      "Jayanthi Kumaresh",
      "Pravin Godkhindi"
    ],
    "venue": {
      "name": "Bharat Kalachar",
      "address": "11, South Mada Street, Mylapore, Chennai 600004",
      "mapEmbedUrl": ""
    },
    "registrationEnabled": true,
    "registrationUrl": "https://bookmyshow.com/events/veena-vaibhavam",
    "image": "",
    "featured": false
  },
  {
    "id": "evt1777219348702",
    "title": "Shatadhara",
    "date": "2026-04-30",
    "time": "09:00",
    "category": "Other",
    "artists": [
      "Ganesh"
    ],
    "description": "Extempore poetry",
    "venue": {
      "name": "Mangala Mantapa",
      "address": "Bengaluru",
      "mapEmbedUrl": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3888.624362724546!2d77.57958367411969!3d12.931847615750497!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1599c4ca5479%3A0xdaa09fed06a15a7d!2sMangala%20Mantapa!5e0!3m2!1sen!2sin!4v1777219263637!5m2!1sen!2sin\""
    },
    "registrationEnabled": true,
    "registrationUrl": "https://app.startmessaging.com/onboarding",
    "featured": false,
    "image": ""
  },
  {
    "id": "evt1777262689871",
    "title": "OK",
    "date": "2026-05-29",
    "time": "03:03",
    "category": "Carnatic Vocal",
    "artists": [
      "Noone",
      "someone",
      "anyone"
    ],
    "description": "Good one.",
    "venue": {
      "name": "DK",
      "address": "",
      "mapEmbedUrl": ""
    },
    "registrationEnabled": false,
    "registrationUrl": "",
    "featured": true,
    "image": ""
  },
  {
    "id": "evt1778301305905",
    "title": "adasd",
    "date": "2026-05-30",
    "time": "09:00",
    "category": "Avadhāna​",
    "artists": [
      "adasd"
    ],
    "description": "asda",
    "venue": {
      "name": "GIPA",
      "address": "blr",
      "mapEmbedUrl": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3888.503160906577!2d77.56419327411979!3d12.93962271558045!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae158b9049dfd5%3A0xf18422c3361a4d49!2sGokhale%20Institute%20of%20Public%20Affairs!5e0!3m2!1sen!2sin!4v1778300461704!5m2!1sen!2sin"
    },
    "registrationEnabled": false,
    "registrationUrl": "",
    "featured": false,
    "image": ""
  },
  {
    "id": "evt1778302905041",
    "title": "fdsaf",
    "date": "2026-05-30",
    "time": "09:00",
    "category": "Avadhāna​",
    "artists": [
      "sdfsdf"
    ],
    "description": "ghrtyurtbge",
    "venue": {
      "name": "ertregdg",
      "address": "bxgvbdsb",
      "mapEmbedUrl": "https://www.google.com/search?q=304+error+code&oq=304+error+code&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDM0NjRqMGo0qAIAsAIB&sourceid=chrome&ie=UTF-8"
    },
    "registrationEnabled": true,
    "registrationUrl": "https://www.google.com/search?q=304+error+code&oq=304+error+code&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDM0NjRqMGo0qAIAsAIB&sourceid=chrome&ie=UTF-8",
    "featured": true,
    "image": ""
  },
  {
    "id": "evt1778303102761",
    "title": "jgfgasdf",
    "date": "2026-04-27",
    "time": "09:00",
    "category": "Avadhāna​",
    "artists": [
      "sdfggfha"
    ],
    "description": "gdfgfdhgfhdhg",
    "venue": {
      "name": "sadfgfdgh",
      "address": "dfdfdhfdg",
      "mapEmbedUrl": ""
    },
    "registrationEnabled": true,
    "registrationUrl": "https://www.google.com/search?q=304+error+code&oq=304+error+code&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDM0NjRqMGo0qAIAsAIB&sourceid=chrome&ie=UTF-8",
    "featured": false,
    "image": ""
  },
  {
    "id": "evt1778303593449",
    "title": "afaasdfasfg",
    "date": "2026-06-02",
    "time": "09:00",
    "category": "Avadhāna​",
    "artists": [
      "sdfasdf"
    ],
    "description": "sadfgfgddg",
    "venue": {
      "name": "fdfgdfg",
      "address": "gdfgfdgdfg",
      "mapEmbedUrl": ""
    },
    "registrationEnabled": true,
    "registrationUrl": "https://www.google.com/search?q=304+error+code&oq=304+error+code&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDM0NjRqMGo0qAIAsAIB&sourceid=chrome&ie=UTF-8",
    "featured": true,
    "image": ""
  },
  {
    "id": "evt1778307971874",
    "title": "Something",
    "date": "2026-05-30",
    "time": "09:00",
    "category": "Bharatanāṭyaṃ",
    "artists": [
      "Me"
    ],
    "description": "I don't dance",
    "venue": {
      "name": "GIPA",
      "address": "Blr",
      "mapEmbedUrl": "Request URL https://rasaaraadhanam.netlify.app/admin-config.js Request Method GET Status Code 404 Not Found"
    },
    "registrationEnabled": false,
    "registrationUrl": "",
    "featured": false,
    "image": ""
  }
];
